<?php
/*
* MLMI Builder
* Advanced Custom Fields — Basic fields
*/

if (function_exists('acf_add_local_field_group')):

/*
* MLMI Builder
*/
acf_add_local_field_group(array(
	'key' => 'group_58c995780089f',
	'title' => '[MLMI Builder]',
	'fields' => array(
		array(
			'key' => 'field_58c9bc591d5ad',
			'label' => __('MLMI Builder', 'mlmi-builder'),
			'name' => 'sections',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'mlmi-builder-section',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 1,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Ajouter une section',
			'sub_fields' => array(
				array(
					'key' => 'field_58c9bc921d5ae',
					'label' => 'Section',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_58c9bec55d27f',
					'label' => 'Rangées',
					'name' => 'rows',
					'type' => 'flexible_content',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => 'mlmi-builder-row',
						'id' => '',
					),
					'layouts' => array(
						'58c9c58520c48' => array(
							'key' => '58c9c58520c48',
							'name' => 'text_row',
							'label' => 'Rangée standard',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_58c9c59420c49',
									'label' => 'Rangées',
									'name' => 'rows',
									'type' => 'clone',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'clone' => array(
										0 => 'group_58c9bff040a3f',
									),
									'display' => 'seamless',
									'layout' => 'block',
									'prefix_label' => 0,
									'prefix_name' => 0,
								),
							),
							'min' => '',
							'max' => '',
						),
						'58d00e6899b7b' => array(
							'key' => '58d00e6899b7b',
							'name' => 'code_row',
							'label' => 'Rangée programmée',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_58d00e6899b7c',
									'label' => 'Rangées',
									'name' => 'rows',
									'type' => 'clone',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'clone' => array(
										0 => 'group_58cbf980a57a0',
									),
									'display' => 'seamless',
									'layout' => 'block',
									'prefix_label' => 0,
									'prefix_name' => 0,
								),
							),
							'min' => '',
							'max' => '',
						),
						'5b2c05101cc5a' => array(
							'key' => '5b2c05101cc5a',
							'name' => 'gallery',
							'label' => 'Galerie d\'images',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_5b2c05141cc5b',
									'label' => 'Rangées',
									'name' => 'rows',
									'type' => 'clone',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'clone' => array(
										0 => 'group_58d01060dff6c',
									),
									'display' => 'seamless',
									'layout' => 'block',
									'prefix_label' => 0,
									'prefix_name' => 0,
								),
							),
							'min' => '',
							'max' => '',
						),
					),
					'button_label' => 'Ajouter une rangée',
					'min' => '',
					'max' => '',
				),
				array(
					'key' => 'field_58c9bcb71d5af',
					'label' => 'Présentation',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_58c9bdfe6e16d',
					'label' => 'ID',
					'name' => 'section_id',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_58cac9b06d958',
					'label' => 'Classes',
					'name' => 'section_class',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
			array(
				'param' => 'post_taxonomy',
				'operator' => '!=',
				'value' => 'category:non-classe',
			),
			array(
				'param' => 'post_taxonomy',
				'operator' => '!=',
				'value' => 'category:non-classe',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array(
				'param' => 'post_template',
				'operator' => '==',
				'value' => 'default',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'views/template-custom.blade.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'custom_fields',
		2 => 'discussion',
		3 => 'comments',
		4 => 'slug',
		5 => 'format',
		6 => 'tags',
		7 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

/*
* Content Type — Galerie de photos
*/
acf_add_local_field_group(array(
	'key' => 'group_58d01060dff6c',
	'title' => '[MLMI Builder] Galerie de photos',
	'fields' => array(
		array(
			'key' => 'field_58d010674ed8e',
			'label' => 'Galerie d\'images',
			'name' => 'gallery',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'insert' => 'append',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'jpg, jpeg',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));

/*
* Content Type — Rangée photo
*/
acf_add_local_field_group(array(
	'key' => 'group_58cabc52d2b29',
	'title' => '[MLMI Builder] Rangée photo',
	'fields' => array(
		array(
			'key' => 'field_58cabc6002ac0',
			'label' => 'Photo principale',
			'name' => 'photo',
			'type' => 'image',
			'instructions' => 'Fichier jpeg d\'un minimum 2000px de large.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '67',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => 1000,
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'jpg, jpeg',
		),
		array(
			'key' => 'field_58cabcb702ac1',
			'label' => 'Photo mobile',
			'name' => 'photo_mobile',
			'type' => 'image',
			'instructions' => 'Image pour la version mobile. Si aucune image n\'est fournie, la version originale de l\'image est automatiquement découpée pour format mobile.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => 960,
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'jpg, jpeg',
		),
		array(
			'key' => 'field_58cd584dfe642',
			'label' => 'Légende',
			'name' => 'display_legend',
			'type' => 'true_false',
			'instructions' => 'Afficher la légende sous la bande photo.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '67',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));

/*
* Content Type — Rangée programmée (shortcode)
*/
acf_add_local_field_group(array(
	'key' => 'group_58cbf980a57a0',
	'title' => '[MLMI Builder] Rangée programmée',
	'fields' => array(
		array(
			'key' => 'field_58cbf9861628a',
			'label' => 'Code',
			'name' => 'shortcode',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));

/*
* Content Type — Rangée standard
*/
acf_add_local_field_group(array(
	'key' => 'group_58c9bff040a3f',
	'title' => '[MLMI Builder] Rangée standard',
	'fields' => array(
		array(
			'key' => 'field_58c9c4401c35c',
			'label' => 'Colonnes',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_58c9c84db930a',
			'label' => 'Colonne 1',
			'name' => 'col_1',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.333',
				'class' => 'mlmi-builder-column',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_58c9c879b930b',
			'label' => 'Colonne 2',
			'name' => 'col_2',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58c9c3c51c35a',
						'operator' => '==',
						'value' => '2',
					),
				),
				array(
					array(
						'field' => 'field_58c9c3c51c35a',
						'operator' => '==',
						'value' => '3',
					),
				),
			),
			'wrapper' => array(
				'width' => '33.333',
				'class' => 'mlmi-builder-column',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_58c9c89eb930e',
			'label' => 'Colonne 3',
			'name' => 'col_3',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58c9c3c51c35a',
						'operator' => '==',
						'value' => '3',
					),
				),
			),
			'wrapper' => array(
				'width' => '33.333',
				'class' => 'mlmi-builder-column',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_58c9c42e1c35b',
			'label' => 'Options',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_58c9c3c51c35a',
			'label' => 'Nombre de colonnes',
			'name' => 'cols_num',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => 'select-cols-number',
				'id' => '',
			),
			'choices' => array(
				1 => '1 colonne',
				2 => '2 colonnes',
				3 => '3 colonnes',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_58cab977c077c',
			'label' => 'Configuration des colonnes',
			'name' => 'cols_config',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58c9c3c51c35a',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => 'cols_config',
				'id' => '',
			),
			'choices' => array(
				6 => 'Pleine largeur',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_58cab91fc077b',
			'label' => 'Configuration des colonnes',
			'name' => 'cols_config',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58c9c3c51c35a',
						'operator' => '==',
						'value' => '2',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => 'cols_config',
				'id' => '',
			),
			'choices' => array(
				'3-3' => 'Moitié-moitié',
				'2-4' => '1 / 2',
				'4-2' => '2 / 1',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '3-3',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_58cab993c077d',
			'label' => 'Configuration des colonnes',
			'name' => 'cols_config',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58c9c3c51c35a',
						'operator' => '==',
						'value' => '3',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => 'cols_config',
				'id' => '',
			),
			'choices' => array(
				'2-2-2' => 'Trois colonnes',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '2-2-2',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_59e4ce0692e5d',
			'label' => 'Options colonne 1',
			'name' => 'col_1_option',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58c9c3c51c35a',
						'operator' => '==',
						'value' => '1',
					),
				),
				array(
					array(
						'field' => 'field_58c9c3c51c35a',
						'operator' => '==',
						'value' => '2',
					),
				),
				array(
					array(
						'field' => 'field_58c9c3c51c35a',
						'operator' => '==',
						'value' => '3',
					),
				),
			),
			'wrapper' => array(
				'width' => '33.333',
				'class' => 'mlmi-builder-column-option',
				'id' => '',
			),
			'choices' => array(
				'push' => 'Pousser vers le bas',
				'pull' => 'Tirer vers le haut',
				'video' => 'Contenu vidéo',
				'under' => 'Sous les lignes',
				'overflow' => 'Dépassement',
				'order-first' => 'En premier',
				'order-second' => 'En deuxième',
				'order-third' => 'En dernier',
				'center' => 'Centrer le bloc contenu',
				'padding-right' => 'Espace à droite',
				'padding-left' => 'Espace à gauche',
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_59e4ce4f92e60',
			'label' => 'Options colonne 2',
			'name' => 'col_2_option',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58c9c3c51c35a',
						'operator' => '==',
						'value' => '2',
					),
				),
				array(
					array(
						'field' => 'field_58c9c3c51c35a',
						'operator' => '==',
						'value' => '3',
					),
				),
			),
			'wrapper' => array(
				'width' => '33.333',
				'class' => 'mlmi-builder-column-option',
				'id' => '',
			),
			'choices' => array(
				'push' => 'Pousser vers le bas',
				'pull' => 'Tirer vers le haut',
				'video' => 'Contenu vidéo',
				'under' => 'Sous les lignes',
				'double' => 'Élargissement',
				'order-first' => 'En premier',
				'order-second' => 'En deuxième',
				'order-third' => 'En dernier',
				'center' => 'Centrer le bloc contenu',
				'padding-right' => 'Espace à droite',
				'padding-left' => 'Espace à gauche',
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_59e4ce6192e61',
			'label' => 'Options colonne 3',
			'name' => 'col_3_option',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58c9c3c51c35a',
						'operator' => '==',
						'value' => '3',
					),
				),
			),
			'wrapper' => array(
				'width' => '33.333',
				'class' => 'mlmi-builder-column-option',
				'id' => '',
			),
			'choices' => array(
				'push' => 'Pousser vers le bas',
				'pull' => 'Tirer vers le haut',
				'video' => 'Contenu vidéo',
				'under' => 'Sous les lignes',
				'overflow' => 'Dépassement',
				'order-first' => 'En premier',
				'order-second' => 'En deuxième',
				'order-third' => 'En dernier',
				'center' => 'Centrer le bloc contenu',
				'padding-right' => 'Espace à droite',
				'padding-left' => 'Espace à gauche',
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_58cacac3c8c37',
			'label' => 'ID',
			'name' => 'row_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => 'clear-left',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_58cacaebc8c38',
			'label' => 'Classes',
			'name' => 'row_class',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_58cb5252d1b7d',
			'label' => 'Espace bas',
			'name' => 'padding_bottom',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'4em' => 'Par défaut (4em)',
				'fitted' => 'Aucun (0)',
			),
			'default_value' => array(
				0 => '4em',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));

endif;
